### ISSUE TITLE
Responsiveness of the safety start screens

### ISSUE THREAD

**Issue by PaulCaillau** [ArkEcosystem/desktop-wallet#629] opened 2018-12-03 21:12 UTC
**Describe the bug**
Responsivness problem on Desktop Wallet V2 start screens
 
**To Reproduce**
1. Download and install the Desktop Wallet V2
2. Safety start screens prompt and here are the lack of responsiveness.
3. Reset data and open your wallet App again if already set up.

**Expected behavior**
I expected the buttons to be correctly placed on my screen when it is not on fullscreen. Also amazing Oleg work is not correctly resized with my screen.

**Screenshots**
Cannot take a screenshot

**Server (please complete the following information):**
 - OS: Windows x64
 - Version: Windows 10

**Additional context**
The design is slick ! great work

**Comment by j-a-m-l** [comment] 2018-12-04 14:49
I confirm that the problem is on Linux too: buttons were move to different places on each step.

**Comment by ItsANameToo** [comment] 2018-12-04 16:54
@PaulCaillau can you specify the screen size you used when you experienced this?

**Comment by ItsANameToo** [comment] 2018-12-04 16:56
<img width="1077" alt="intro" src="https://user-images.githubusercontent.com/35610748/49458802-d3f29380-f7ed-11e8-9f85-29600d866017.png">

I'm unable to reproduce this, even on a small screen size, so maybe it's a windows / linux issue

**Comment by ItsANameToo** [comment] 2018-12-16 12:55
Fixed by #761

**Closed by ItsANameToo** 2018-12-16 12:55 UTC
Labels: Type: Bug
