### ISSUE TITLE
News obscures buttons

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/desktop-wallet#561] opened 2018-02-11 04:52 UTC
![image](https://user-images.githubusercontent.com/2704733/36068665-281d2e64-0e8f-11e8-8111-a42e027780bd.png)

The window is scrolled all the way to the bottom.

Move buttons? or Move News?

**Comment by j-a-m-l** [comment] 2018-02-12 21:59
Could you elaborate about this? Is it the dashboard / home screen?

**Comment by vRobM** [comment] 2018-02-13 03:13
It happens on every screen when there is news. The screen shot for the buttons being obscured is the manage networks view.
If the news was on top or either side it would interfere less.

**Comment by Nasicus** [comment] 2018-02-13 06:02
But only on very very small window sozes right?

**Comment by vRobM** [comment] 2018-02-13 07:02
It is less of an issue full screen, but I don't use any apps full screen.
At even 3/4 the window height of the entire screen it still obscures
information at the bottom.

It should behave better at smaller window sizes w/o obscuring info.

++ Rob

About me <https://remote.com/r>

**Comment by vRobM** [comment] 2018-02-15 09:09
No, not only on very very small window sizes,
Here's an example window size which blocks the buttons and the Hand Crafted with Love message at the bottom of the main view:
![image](https://user-images.githubusercontent.com/2704733/36248504-9129c132-11ec-11e8-8ff9-5f5e0203bcee.png)
![image](https://user-images.githubusercontent.com/2704733/36248565-d3e0f2f2-11ec-11e8-930d-590381a7eb18.png)

**Comment by Nasicus** [comment] 2018-02-15 09:24
Why don't you just close them?

I think they are not reopened if you close them once (not 100% sure about that, though I tested it and it seems to work).

**Comment by vRobM** [comment] 2018-02-15 09:56
It comes back.
The issue is the obscuring of usable elements, not whether it's there or not. ;-)

Where else can it go? Why not below the menu bar in a layer underneath the menu?

**Comment by Nasicus** [comment] 2018-02-15 10:44
Well this is just my personal opinion but I find it ok where it is and how the behavior is.
What should be fixed - and apparently doesn't work for you, even though it does for me-  is that it should not reappear after you close the news.

**Comment by zillionn** [comment] 2018-02-15 11:03
md-toast .announcement {
z-index: 1;
}

Shoud fix this.

**Comment by vRobM** [comment] 2018-02-17 08:08
Can we change the status as it seems like we have a potential fix?

**Comment by Nasicus** [comment] 2018-02-17 09:22
Well it is a fix, the question is if this should be the intended behavior ;)
The reason I didn't fix this, is because I don't agree with your statement and proposed solution.
The ark-team probably should agree first on how to solve this and/or if this is a valid solution for them.

**Comment by zillionn** [comment] 2018-02-17 15:36
@Nasicus I don't believe this is so important. I'm using Macbook Pro, which is very common, and even in full screen I can't save any setting because of that footer bar. Do not hesitate to create a PR, it will be accepted.

**Closed** 2018-06-11 18:41 UTC
Labels: Status: Waiting feedback, backlog
