### ISSUE TITLE
Infinite scroll method is inconvenient. 

### ISSUE THREAD

**Issue by plzpickausername** [ArkEcosystem/desktop-wallet#356] opened 2017-10-19 07:05 UTC
Infinite scroll method is inconvenient.
Please make a list of figures.
Many fx wallets need to repeat descending down.
it is inconvenient.

![gzs](https://user-images.githubusercontent.com/32923222/31758164-35e76fd4-b4e7-11e7-968b-53f42b81fe13.png)
Consider adding a numeric list feature.

**Comment by alexbarnsley** [comment] 2017-10-21 18:53
@plzpickausername in what way is it inconvenient, as you've not specifically said why?

**Comment by alexbarnsley** [comment] 2017-10-21 18:59
Worth also pointing out that, unless you have a specific reason, this is a duplicate of #49. That got overruled with infinite scroll based on the attached PR of PR #166

**Comment by krau612** [comment] 2017-10-21 19:02
@alexbarnsley If I understand correctly, it's inconvenient because if an account has a lot of transactions (like thousands) you have to scroll through all of them instead of skipping to the end. It's pretty easy and quick to scroll through 100 or 200 transactions, but it takes time to scroll through 1,000 or 2,000 transactions.

**Comment by alexbarnsley** [comment] 2017-10-21 19:04
@krau612 That's fair enough, thanks! Just wanted a bit more clarification on the issue 🙂 I probably won't work on this (not any time soon at least), but useful for the person who does!

**Comment by j-a-m-l** [comment] 2017-11-17 15:05
I think that we could have both options, similar to some e-commerce sites:
Initially we could display `n` items per page, but show an option "Show all", that would use the infinite scroll behaviour.

**Closed** 2018-06-11 18:28 UTC
Labels: Type: Feature Request, backlog
